/**
 * Recipe Models
 *
 * Type definitions for recipe management in Manager Recipe.
 *
 * @see .kiro/specs/project-restructure/ai-services-design.md - Recipe Management section
 * @see .kiro/specs/project-restructure/social-requirements.md - Recipe Picker integration
 */

/**
 * Recipe source type
 * - ai: Generated by AI
 * - manual: Created manually by user
 * - imported: Imported from external source
 * - saved: Saved from social post (another user's recipe)
 */
export type RecipeSource = 'ai' | 'manual' | 'imported' | 'saved';

/**
 * Recipe difficulty level
 */
export type RecipeDifficulty = 'easy' | 'medium' | 'hard';

/**
 * Recipe ingredient with Vietnamese and English translations
 * Note: Ingredients are ALREADY TRANSLATED by lookup.handler (task 5.5.4)
 */
export interface RecipeIngredient {
  /** Vietnamese name (original input) */
  vietnamese: string;

  /** English translation (from Dictionary/Translation Cache/AI) */
  english: string;

  /** Amount (e.g., "500g", "2 cups", "1 tbsp") */
  amount: string;

  /** Optional notes (e.g., "chopped", "diced", "minced") */
  notes?: string;
}

/**
 * Recipe cooking step
 */
export interface RecipeStep {
  /** Step number (1-based) */
  stepNumber: number;

  /** Step description */
  description: string;

  /** Step images (max 3 per step) */
  images?: string[];

  /** Estimated duration in minutes */
  duration?: number;
}

/**
 * Recipe images structure
 */
export interface RecipeImages {
  /** Completed dish image (required) */
  completed: string;

  /** Step images (2 per step) */
  steps?: string[][];
}

/**
 * Recipe nutrition information
 */
export interface RecipeNutrition {
  /** Calories per serving */
  calories: number;

  /** Protein in grams per serving */
  protein: number;

  /** Carbohydrates in grams per serving */
  carbs: number;

  /** Fat in grams per serving */
  fat: number;

  /** Fiber in grams per serving */
  fiber?: number;

  /** Sodium in milligrams per serving */
  sodium?: number;

  /** Sugar in grams per serving */
  sugar?: number;
}

/**
 * Recipe attribution for imported recipes
 */
export interface RecipeAttribution {
  /** Original author's user ID (immutable) */
  originalAuthorId: string;

  /** Original author's username (immutable, text-only) */
  originalAuthorUsername: string;

  /** Import timestamp */
  importedAt: number;
}

/**
 * Recipe entity in DynamoDB (Manager Recipe)
 * Note: Different from AI-generated Recipe in suggestion.model.ts
 */
export interface RecipeEntity {
  /** Partition key: RECIPE#{recipeId} */
  PK: string;

  /** Sort key: METADATA */
  SK: string;

  /** Recipe ID (UUID) */
  recipeId: string;

  /** Recipe title */
  title: string;

  /** Recipe description */
  description?: string;

  /** Recipe ingredients (ALREADY TRANSLATED) */
  ingredients: RecipeIngredient[];

  /** Cooking steps */
  steps: RecipeStep[];

  /** Recipe images */
  images: RecipeImages;

  /** Number of servings */
  servings: number;

  /** Total cooking time in minutes */
  cookingTime: number;

  /** Recipe difficulty */
  difficulty: RecipeDifficulty;

  /** Recipe source */
  source: RecipeSource;

  /** Attribution for imported recipes (immutable) */
  attribution?: RecipeAttribution;

  /** Nutrition information */
  nutrition?: RecipeNutrition;

  /** Recipe author (user ID) */
  authorId: string;

  /** Whether recipe is marked as favorite */
  isFavorite?: boolean;

  /** Whether recipe is shared to social feed */
  isShared: boolean;

  /** Shared post ID (if shared) */
  sharedPostId?: string;

  /** Recipe creation timestamp */
  createdAt: number;

  /** Recipe last update timestamp */
  updatedAt: number;

  /** GSI1 partition key: USER#{userId} (for user's recipes) */
  GSI1PK: string;

  /** GSI1 sort key: RECIPE#{createdAt} (for sorting) */
  GSI1SK: string;

  /** Entity type for filtering */
  entityType: 'RECIPE';
}

/**
 * Recipe summary for Recipe Picker (optimized projection)
 */
export interface RecipeSummary {
  /** Recipe ID */
  recipeId: string;

  /** Recipe title */
  title: string;

  /** Thumbnail image (completed dish) */
  thumbnail: string;

  /** Number of ingredients */
  ingredientsCount: number;

  /** Number of servings */
  servings: number;

  /** Total cooking time in minutes */
  cookingTime: number;

  /** Recipe difficulty */
  difficulty: RecipeDifficulty;

  /** Recipe creation timestamp */
  createdAt: number;

  /** Whether recipe is marked as favorite */
  isFavorite?: boolean;

  /** Whether recipe is shared to social feed */
  isShared: boolean;

  /** Shared post ID (if shared) */
  sharedPostId?: string | null;

  /** Recipe source (ai, manual, imported) */
  source?: RecipeSource;
}

/**
 * Recipe details for sharing (full recipe data)
 */
export interface RecipeDetails {
  /** Recipe ID */
  recipeId: string;

  /** Recipe title */
  title: string;

  /** Recipe description */
  description?: string;

  /** Recipe images */
  images: RecipeImages;

  /** Recipe ingredients */
  ingredients: RecipeIngredient[];

  /** Cooking steps */
  steps: RecipeStep[];

  /** Nutrition information */
  nutrition?: RecipeNutrition;

  /** Number of servings */
  servings: number;

  /** Total cooking time in minutes */
  cookingTime: number;

  /** Recipe difficulty */
  difficulty: RecipeDifficulty;

  /** Recipe source */
  source: RecipeSource;

  /** Attribution for imported recipes */
  attribution?: RecipeAttribution;

  /** Whether recipe is marked as favorite */
  isFavorite?: boolean;
}

/**
 * Create recipe request
 */
export interface CreateRecipeRequest {
  /** Recipe title */
  title: string;

  /** Recipe description */
  description?: string;

  /** Recipe ingredients (ALREADY TRANSLATED) */
  ingredients: RecipeIngredient[];

  /** Cooking steps */
  steps: RecipeStep[];

  /** Recipe images */
  images: RecipeImages;

  /** Number of servings */
  servings: number;

  /** Total cooking time in minutes */
  cookingTime: number;

  /** Recipe difficulty */
  difficulty: RecipeDifficulty;

  /** Recipe source */
  source: RecipeSource;

  /** Attribution for imported recipes */
  attribution?: RecipeAttribution;

  /** Nutrition information */
  nutrition?: RecipeNutrition;
}

/**
 * Update recipe request
 */
export interface UpdateRecipeRequest {
  /** Recipe title */
  title?: string;

  /** Recipe description */
  description?: string;

  /** Recipe ingredients */
  ingredients?: RecipeIngredient[];

  /** Cooking steps */
  steps?: RecipeStep[];

  /** Recipe images */
  images?: RecipeImages;

  /** Number of servings */
  servings?: number;

  /** Total cooking time in minutes */
  cookingTime?: number;

  /** Recipe difficulty */
  difficulty?: RecipeDifficulty;

  /** Nutrition information */
  nutrition?: RecipeNutrition;

  /** Favorite status */
  isFavorite?: boolean;
}

/**
 * Get user recipes request (Recipe Picker)
 */
export interface GetUserRecipesRequest {
  /** User ID */
  userId: string;

  /** Search query (optional) */
  search?: string;

  /** Filter by difficulty (optional) */
  difficulty?: RecipeDifficulty;

  /** Filter by shared status (optional) */
  isShared?: boolean;

  /** Pagination limit */
  limit?: number;

  /** Pagination cursor (lastEvaluatedKey) */
  cursor?: string;
}

/**
 * Get user recipes response (Recipe Picker)
 */
export interface GetUserRecipesResponse {
  /** Recipe summaries */
  recipes: RecipeSummary[];

  /** Total count */
  total: number;

  /** Whether there are more recipes */
  hasMore: boolean;

  /** Next cursor for pagination */
  nextCursor?: string;
}
